### ISSUE TITLE
CSS: konstig outline på kort när redigering sker.

### ISSUE THREAD

**Issue by anthonwellsjo** [anthonwellsjo/Kanban-Meta-Grupp-3#23]

**Comment by SamirWU20** [comment]
Så här ser det ut efter den ändring @firefool gjort.
![2020-10-13-155310](https://user-images.githubusercontent.com/70319717/95869981-429ac380-0d6c-11eb-8828-cd9fe5aa390c.png)

Är det fortfarande konstigt eller ser det bra ut @anthonwellsjo ?
