### ISSUE TITLE
CSS: grådassig bakgrund på edit och save-knappar

### ISSUE THREAD

**Issue by anthonwellsjo** [anthonwellsjo/Kanban-Meta-Grupp-3#24]

**Comment by SamirWU20** [comment]
Så här ser det ut hos mig just nu:
![2020-10-13-155552](https://user-images.githubusercontent.com/70319717/95870315-a8874b00-0d6c-11eb-9ec0-790c735cff22.png)

Jag är inne och tittar på den PR som @firefool begärt. Är det att du vill ha "grådassig bakgrund" eller att du inte vill ha det? Jag ser inte någon grådassig bakgrund just nu. Inte i det PR som firefool kommit med, och mig veterligen inte i dev heller.
