### ISSUE TITLE
CSS : Lista med issues

### ISSUE THREAD

**Issue by anthonwellsjo** [anthonwellsjo/Kanban-Meta-Grupp-3#28]
Följande issues snubblade jag över när jag jobbade på annat:

- [x] .logo-keeper{ ...} är class="logo-kee**e**per i html:en... dvs de samtalar inte med varandra.
- [x] .wrapper är egentligen ett id, dvs. **#**wrapper.

Jag låter någon annan ta en titt djupare inti detta.

MVH

**Comment by kerstinmarie** [comment]
Har redan tagit bort felet med med logo-keeper. Har nu även ändrat .wrapper till #wrapper i ccs-koden kommer i nästa pull request.
