### ISSUE TITLE
Error när man börjar redigera ett kort och sedan tar bort det

### ISSUE THREAD

**Issue by firefool** [anthonwellsjo/Kanban-Meta-Grupp-3#60]
Beror troligtvis på att eventlistner för att märka om man klickar utanför ett kort skapas och sen försöker köra sin funktion efter att kortet som skapade den är borttaget.

**Comment by SamirWU20** [comment]
![2020-10-14-170453](https://user-images.githubusercontent.com/70319717/96104907-adb5d880-0ed9-11eb-9c5d-613c29552e52.png)

**Comment by SamirWU20** [comment]
Problemet är alltså att konsollen skriker. Men den ser inte ut att skrika hela tiden eller i alla lägen.

**Comment by SamirWU20** [comment]
Det kommer även fram när man är inne på inloggningssidan.

![2020-10-15-114026](https://user-images.githubusercontent.com/70319717/96106265-4d279b00-0edb-11eb-8d98-f4a42eb114b9.png)

**Comment by SamirWU20** [comment]
Som jag kunde se så var det olika anrop om man klickade på Save knappen vs. om man klickade utanför kortet för att spara ändringar. Och i vissa fall kunde man hamna i fel tillstånd och då började konsollen skrika oavsett var man klickade. Men det ser ut att fungera konsistent nu med den nya lösningen i #68.
