### ISSUE TITLE
Flytta knappen för att logga in till höger

### ISSUE THREAD

**Issue by kerstinmarie** [anthonwellsjo/Kanban-Meta-Grupp-3#62]
Flytta knappen för att logga in till höger då spara knappen är borttagen.

**Comment by SamirWU20** [comment]
Behöver vi ingen knapp längre för att spara ändringar? Ska ändringar sparas automatiskt nu?

**Comment by SamirWU20** [comment]
Ändringar sparas automatiskt nu. Ingen knapp behövs längre för att spara. Ny implementering i gjord i PR #67.
