### ISSUE TITLE
När kort laddas från localStorage så skapas det en blank rad i toppen av kortet och även i toppen av kolumnen (se bild)

### ISSUE THREAD

**Issue by firefool** [anthonwellsjo/Kanban-Meta-Grupp-3#63]
![board2](https://user-images.githubusercontent.com/3358928/96088004-1050a980-0ec5-11eb-8157-479c9f06f6cb.png)
![board1](https://user-images.githubusercontent.com/3358928/96088005-10e94000-0ec5-11eb-8ba1-18bd6c5a5477.png)

**Comment by SamirWU20** [comment]
Den här kan vara relaterad till issue #66.
